<#
.SYNOPSIS
    Regenerates installer/HostFilesGenerated.wxi from the published host
    output, listing every file other than OpenReader.exe / OpenReader.dll
    (which are declared explicitly in Product.wxs).

.DESCRIPTION
    Run after publishing the host:

        dotnet publish src/ReaderHost.Windows -c Release -r win-x64 `
            --self-contained false -o publish/host
        pwsh scripts/regenerate-installer-files.ps1

    The output is deterministic: files are sorted by name and component
    GUIDs use a stable derivation so the resulting MSI is reproducible.

    Component GUIDs use WiX's '*' (auto-generated), which makes the MSI
    NOT byte-for-byte stable between builds, but is the simplest option
    for a first cut. Switch to derived GUIDs when supply-chain pinning
    matters.
#>
[CmdletBinding()]
param(
    [string]$PublishDir = (Join-Path $PSScriptRoot '..\publish\host'),
    [string]$Output     = (Join-Path $PSScriptRoot '..\installer\HostFilesGenerated.wxi')
)

$ErrorActionPreference = 'Stop'
$publishFull = (Resolve-Path $PublishDir).Path

$skip = @('OpenReader.exe', 'OpenReader.dll')
$files = Get-ChildItem -LiteralPath $publishFull -Recurse -File |
    Where-Object { $skip -notcontains $_.Name } |
    Sort-Object FullName

$ns  = 'http://wixtoolset.org/schemas/v4/wxs'
$sb  = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('<?xml version="1.0" encoding="UTF-8"?>')
[void]$sb.AppendLine('<!-- Auto-generated by scripts/regenerate-installer-files.ps1. Do not edit. -->')
[void]$sb.AppendLine("<Include xmlns=`"$ns`">")

foreach ($f in $files) {
    $rel = $f.FullName.Substring($publishFull.Length).TrimStart('\','/')
    $id  = ($rel -replace '[^A-Za-z0-9_]', '_')
    if ($id.Length -gt 64) { $id = $id.Substring($id.Length - 64) }
    $compId = "C_$id"
    [void]$sb.AppendLine("  <Component Id=`"$compId`" Guid=`"*`">")
    [void]$sb.AppendLine("    <File Source=`"$rel`" KeyPath=`"yes`" />")
    [void]$sb.AppendLine('  </Component>')
}

[void]$sb.AppendLine('</Include>')

$outFull = Resolve-Path -ErrorAction SilentlyContinue $Output
if (-not $outFull) { $outFull = $Output }
[System.IO.File]::WriteAllText($outFull, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $($files.Count) component entries to $Output"
